Repository theohbrothers/docker-php, pull requests merged in 2023-09, with the labels that each got.

#30 Enhancement: Remove alpine version suffix from tag name
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/VARIANTS.ps1
  variants/7.2.34-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets-xdebug/Dockerfile
  variants/7.2.34-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets/Dockerfile
  variants/7.2.34-fpm-alpine/Dockerfile
  variants/7.3.33-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets-xdebug/Dockerfile
  variants/7.3.33-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets/Dockerfile
  variants/7.3.33-fpm-alpine/Dockerfile
  variants/7.4.33-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets-xdebug/Dockerfile
  variants/7.4.33-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets/Dockerfile
  variants/7.4.33-fpm-alpine/Dockerfile
  variants/8.0.29-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets-xdebug/Dockerfile
  variants/8.0.29-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets/Dockerfile
  variants/8.0.29-fpm-alpine/Dockerfile
  variants/8.1.20-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets-xdebug/Dockerfile
  variants/8.1.20-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets/Dockerfile
  variants/8.1.20-fpm-alpine/Dockerfile
  variants/8.2.7-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets-xdebug/Dockerfile
  variants/8.2.7-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets/Dockerfile
  variants/8.2.7-fpm-alpine/Dockerfile
Labels: enhancement

#31 Refactor: Move versions from `VARIANTS.ps1` to `versions.json`
  generate/definitions/VARIANTS.ps1
  generate/definitions/versions.json
Labels: refactor

#32 Enhancement (ci): Add `Update-Versions.ps1` and `cron` job
  .github/workflows/cron.yml
  Update-Versions.ps1
  generate/definitions/FILES.ps1
  generate/templates/.github/workflows/cron.yml.ps1
Labels: enhancement

#33 Enhancement (ci): Add `on: merge_group` for merge queue support
  .github/workflows/ci-master-pr.yml
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: enhancement

#35 Enhancement: Bump v8.1 variants to v8.1.23
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/8.1.23-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets-xdebug/Dockerfile
  variants/8.1.23-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets/Dockerfile
  variants/8.1.23-fpm-alpine/Dockerfile
Labels: enhancement

#36 Enhancement: Bump v8.0 variants to v8.0.30
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/8.0.30-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets-xdebug/Dockerfile
  variants/8.0.30-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets/Dockerfile
  variants/8.0.30-fpm-alpine/Dockerfile
Labels: enhancement

#34 Enhancement: Bump v8.2 variants to v8.2.10
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/8.2.10-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets-xdebug/Dockerfile
  variants/8.2.10-fpm-alpine-opcache-mysqli-gd-pdo-memcached-sockets/Dockerfile
  variants/8.2.10-fpm-alpine/Dockerfile
Labels: enhancement

#38 Docs (readme): Update Variant versions section
  README.md
  generate/templates/README.md.ps1
Labels: docs

#39 Enhancement (ci): Remove ` $env:GITHUB_TOKEN` in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: enhancement

#40 Refactor (ci): Use new `versions.json` config
  Update-Versions.ps1
  generate/definitions/VARIANTS.ps1
  generate/definitions/versions.json
Labels: refactor

#41 Style: Format `versions.json`
  generate/definitions/versions.json
Labels: style

#42 Enhancement (ci): Add `workflow_dispatch` to `cron` job
  .github/workflows/cron.yml
  generate/templates/.github/workflows/cron.yml.ps1
Labels: enhancement

#43 Enhancement (ci): Add support for incremental variants
  .github/workflows/ci-master-pr.yml
  generate/definitions/VARIANTS.ps1
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
  generate/templates/Dockerfile.ps1
Labels: enhancement

#44 Refactor (ci): Use a `job_group_key` to group jobs
  .github/workflows/ci-master-pr.yml
  .vscode/tasks.json
  generate/definitions/VARIANTS.ps1
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: refactor
